version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    links:
      - consul
    ports:
      - "8080:8080"
    labels:
      SERVICE_IGNORE: 'yes'
  consul:
    command: -server -bootstrap -advertise ${HOST_IP}
    image: progrium/consul
    container_name: consul
    logging:
        driver: json-file
    labels:
      SERVICE_IGNORE: 'yes'
    ports:
      - "8500:8500"
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  product:
    image: product:latest
    logging:
       driver: json-file
    labels:
      SERVICE_IGNORE: 'yes'
  images:
    image: images:latest
    logging:
       driver: json-file
    labels:
      SERVICE_IGNORE: 'yes'
  ecommerce:
    image: ecommerce:latest
    logging:
       driver: json-file
    labels:
      SERVICE_IGNORE: 'yes'
  zipkin:
    image: openzipkin/zipkin
    logging:
       driver: json-file
    labels:
      SERVICE_IGNORE: 'yes'
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411      