version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    links:
      - consul
    ports:
      - "8080:80"
    labels:
      SERVICE_IGNORE: 'yes'
  consul:
    command: -server -bootstrap -advertise ${HOST_IP}
    image: progrium/consul
    container_name: consul
    logging:
        driver: json-file
    labels:
      SERVICE_IGNORE: 'yes'
    ports:
      - "8500:8500"
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  product:
    image: product:latest
    logging:
       driver: json-file
    labels:
      SERVICE_80_NAME: product
      SERVICE_80_CHECK_HTTP: /
      SERVICE_80_CHECK_INTERVAL: 5s
      SERVICE_443_IGNORE: 'yes'
      SERVICE_TAGS: production
  images:
    image: images:latest
    logging:
       driver: json-file
    labels:
      SERVICE_80_NAME: images
      SERVICE_80_CHECK_HTTP: /
      SERVICE_80_CHECK_INTERVAL: 5s
      SERVICE_443_IGNORE: 'yes'
      SERVICE_TAGS: production
  ecommerce:
    image: ecommerce:latest
    logging:
       driver: json-file
    labels:
      SERVICE_80_NAME: ecommerce
      SERVICE_80_CHECK_HTTP: /
      SERVICE_80_CHECK_INTERVAL: 5s
      SERVICE_443_IGNORE: 'yes'
      SERVICE_TAGS: production